(() => {
  "use strict";
  const MATCH_KEY="steamPartyMatchConfigV1";
  const CONFIG=window.STEAM_PARTY_CONFIG||{},BOARD_CONFIG=CONFIG.board||{};
  const SPACE_COUNT=Number(BOARD_CONFIG.spaces||28),MIN_ROLL=Number(BOARD_CONFIG.diceMin||1),MAX_ROLL=Number(BOARD_CONFIG.diceMax||10),MINIGAME_REWARD=Number(BOARD_CONFIG.minigameReward||10);
  const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
  const view=$("#finalBoardView"),stage=$("#finalBoardStage");if(!view||!stage)return;
  const spacesLayer=$("#finalBoardSpaces"),tokensLayer=$("#finalBoardTokens"),playersList=$("#finalBoardPlayers"),roundText=$("#finalBoardRound"),turnName=$("#finalBoardTurnName"),turnAvatar=$("#finalBoardTurnAvatar"),instruction=$("#finalBoardInstruction"),eventBox=$("#finalBoardEvent"),rollButton=$("#finalRollDice"),diceCube=$("#finalDiceCube"),diceResult=$("#finalDiceResult"),modeBadge=$("#finalBoardModeBadge");
  const minigameOverlay=$("#finalMinigameOverlay"),minigameIntro=$("#finalMinigameIntro"),droneGame=$("#finalDroneGame"),minigameResult=$("#finalMinigameResult"),minigameTitle=$("#finalMinigameTitle"),minigameDescription=$("#finalMinigameDescription"),droneAnswers=$("#finalDroneAnswers"),droneQuestion=$("#finalDroneQuestion"),droneA=$("#finalDroneA"),droneB=$("#finalDroneB"),droneTimer=$("#finalDroneTimer"),minigameWinner=$("#finalMinigameWinner"),minigameRanking=$("#finalMinigameRanking"),matchResultOverlay=$("#finalMatchResultOverlay"),matchRanking=$("#finalMatchRanking");
  const spaceTypes=["start","good","tech","bad","good","challenge","event","good","bad","tech","good","challenge","bad","event","good","tech","bad","good","challenge","event","good","bad","tech","good","challenge","bad","event","good"],spaceSymbols={start:"INÍCIO",good:"+",bad:"−",tech:"T",challenge:"?",event:"!"};
  const colors=["cyan","green","orange","pink","purple","yellow"],shapes=["round","square","triangle","hex"];
  let state=null,rolling=false,droneTimerId=0,droneDeadline=0,currentDroneProblem=null,currentMinigameScores=[];
  const api=()=>window.STEAMParty||{},sleep=ms=>new Promise(r=>setTimeout(r,ms)),randInt=(a,b)=>Math.floor(Math.random()*(b-a+1))+a;
  function toast(m){api().showToast?.(m)}
  function avatarSvg(p){return api().avatarSvg?.(p,true)||`<svg viewBox="0 0 120 120"><rect x="18" y="18" width="84" height="84" rx="34" fill="#65f2c3"/><circle cx="45" cy="53" r="5"/><circle cx="75" cy="53" r="5"/><path d="M43 72 Q60 88 77 72" fill="none" stroke="#082126" stroke-width="4"/></svg>`}
  function boardPath(){const pts=[];for(let x=10;x<=90.01;x+=80/7)pts.push({x,y:10});for(let y=21.5;y<=78.51;y+=57/5)pts.push({x:90,y});for(let x=90;x>=9.99;x-=80/7)pts.push({x,y:90});for(let y=78.5;y>=21.49;y-=57/5)pts.push({x:10,y});return pts.slice(0,SPACE_COUNT)}
  const path=boardPath();
  function renderSpaces(){spacesLayer.innerHTML="";path.forEach((pt,i)=>{const type=spaceTypes[i%spaceTypes.length],el=document.createElement("div");el.className="final-board-space";el.dataset.index=i;el.dataset.type=type;el.style.left=`${pt.x}%`;el.style.top=`${pt.y}%`;el.innerHTML=`<span>${type==="start"?"INÍCIO":spaceSymbols[type]}</span>`;spacesLayer.appendChild(el)})}
  function makePlayer(slot,human,profile,difficulty="normal"){return{slot,id:`p${slot}`,human,bot:!human,name:human?(profile?.name||`Jogador ${slot}`):`Bot ${slot}`,avatarShape:profile?.avatarShape||shapes[(slot-1)%shapes.length],avatarColor:profile?.avatarColor||colors[(slot-1)%colors.length],avatarFace:profile?.avatarFace||(human?"smile":"focus"),difficulty,position:0,laps:0,score:0}}
  function buildPlayers(match){const humans=Math.max(1,Math.min(4,Number(match.humanPlayers||1))),active=api().getActiveProfile?.()||null,players=[];for(let i=1;i<=humans;i++){const profile=i===1?active:{name:`Jogador ${i}`,avatarShape:shapes[(i-1)%shapes.length],avatarColor:colors[(i-1)%colors.length],avatarFace:"smile"};players.push(makePlayer(i,true,profile))}for(let i=humans+1;i<=4;i++){const bot=match.bots?.[i-humans-1]||{};players.push(makePlayer(i,false,null,bot.difficulty||"normal"))}return players}
  const difficultyLabel=v=>({easy:"Fácil",normal:"Normal",hard:"Difícil"}[v]||"Normal");
  function renderPlayers(){playersList.innerHTML="";state.players.forEach((p,i)=>{const row=document.createElement("div");row.className=`final-board-player${i===state.turnIndex?" is-turn":""}`;row.innerHTML=`<span class="final-board-player-avatar">${avatarSvg(p)}</span><span><strong></strong><small></small></span><span class="final-board-player-score"><b>${p.score}</b><span>PTS</span></span>`;$("strong",row).textContent=p.name;$("small",row).textContent=p.bot?`Bot • ${difficultyLabel(p.difficulty)}`:"Humano";playersList.appendChild(row)})}
  function renderTokens(){tokensLayer.innerHTML="";state.players.forEach(p=>{const pt=path[p.position]||path[0],t=document.createElement("div");t.className="final-board-token";t.dataset.playerId=p.id;t.dataset.slot=p.slot;t.style.left=`${pt.x}%`;t.style.top=`${pt.y}%`;t.innerHTML=avatarSvg(p);tokensLayer.appendChild(t)})}
  function updateToken(p){const t=$(`[data-player-id="${p.id}"]`,tokensLayer),pt=path[p.position]||path[0];if(t&&pt){t.style.left=`${pt.x}%`;t.style.top=`${pt.y}%`}}
  function updateTurnUi(){const p=state.players[state.turnIndex];roundText.textContent=`Rodada ${state.round} / ${state.totalRounds}`;turnName.textContent=p.name;turnAvatar.innerHTML=avatarSvg(p);renderPlayers();rollButton.disabled=rolling||p.bot;rollButton.textContent=p.bot?"Bot jogando…":"Rolar dado";instruction.textContent=p.bot?`${p.name} está preparando a jogada.`:"Role o dado para continuar.";diceResult.textContent="";if(p.bot&&!rolling)setTimeout(()=>rollForCurrentPlayer(),650)}
  function updateDiceFaces(result=null){$$('.face',diceCube).forEach((f,i)=>f.textContent=String(i===0&&result?result:randInt(MIN_ROLL,MAX_ROLL)))}
  async function animateDice(result){diceCube.classList.add("rolling");const timer=setInterval(()=>updateDiceFaces(),72);await sleep(800);clearInterval(timer);diceCube.classList.remove("rolling");updateDiceFaces(result);diceCube.style.transform=`rotateX(${randInt(1,3)*360-18}deg) rotateY(${randInt(1,3)*360+28}deg)`;diceResult.textContent=`Saiu ${result}!`;await sleep(360)}
  async function movePlayer(p,steps){for(let i=0;i<steps;i++){const prev=p.position;p.position=(p.position+1)%SPACE_COUNT;if(p.position<prev){p.laps++;p.score+=3;eventBox.textContent=`${p.name} completou uma volta e ganhou +3 Pontos de Missão.`}updateToken(p);await sleep(180)}}
  function resolveSpace(p){const type=spaceTypes[p.position%spaceTypes.length],events={start:()=>`${p.name} passou pela Central de Monitoramento.`,good:()=>{p.score+=3;return`Boa decisão de prevenção! ${p.name} ganhou +3 Pontos de Missão.`},bad:()=>{p.score=Math.max(0,p.score-2);return`Um imprevisto ambiental atrasou a missão. ${p.name} perdeu 2 pontos.`},tech:()=>{p.score+=4;return`Tecnologia de monitoramento encontrada! ${p.name} ganhou +4 pontos.`},challenge:()=>{p.score+=2;return`Casa de desafio! No Alpha, ${p.name} recebe +2 pontos. Os desafios completos virão depois.`},event:()=>{const d=Math.random()<.5?5:-3;p.score=Math.max(0,p.score+d);return d>0?`Evento de resgate bem-sucedido: +${d} pontos para ${p.name}.`:`Evento inesperado: ${p.name} perdeu ${Math.abs(d)} pontos.`}};eventBox.textContent=(events[type]||events.good)();renderPlayers()}
  async function rollForCurrentPlayer(){if(!state||rolling)return;rolling=true;const p=state.players[state.turnIndex];rollButton.disabled=true;const result=randInt(MIN_ROLL,MAX_ROLL);await animateDice(result);await movePlayer(p,result);resolveSpace(p);await sleep(p.bot?700:950);rolling=false;nextTurn()}
  function nextTurn(){state.turnIndex++;if(state.turnIndex>=state.players.length){state.turnIndex=0;endRound();return}updateTurnUi()}
  function endRound(){if(state.match.minigamesEnabled){openMinigame();return}advanceRound()}
  function advanceRound(){if(state.round>=state.totalRounds){finishMatch();return}state.round++;eventBox.textContent=`Rodada ${state.round}. Todos voltam a jogar na mesma ordem.`;updateTurnUi()}
  function compatibleMinigames(){return[{id:"drone-route",title:"Rota do Drone",description:"Calcule a rota direta do drone usando o Teorema de Pitágoras.",controls:["keyboard","phone-touch","phone-motion"],sensorRequired:false}].filter(g=>!(g.sensorRequired&&!state.match.motionMinigamesEnabled)&&(g.controls.includes(state.match.controlMethod)||state.match.mode==="local"))}
  function openMinigame(){const games=compatibleMinigames();if(!games.length){eventBox.textContent="Nenhum minigame compatível nesta rodada. Seguindo para a próxima.";advanceRound();return}const game=games[randInt(0,games.length-1)];state.currentMinigame=game;minigameTitle.textContent=game.title;minigameDescription.textContent=game.description;minigameIntro.classList.remove("hidden");droneGame.classList.add("hidden");minigameResult.classList.add("hidden");minigameOverlay.classList.remove("hidden")}
  const triples=[[3,4,5],[5,12,13],[6,8,10],[8,15,17],[7,24,25],[9,12,15],[12,16,20]];
  function makeDroneProblem(){const[a,b,c]=triples[randInt(0,triples.length-1)],wrong=new Set;while(wrong.size<3){const x=Math.max(1,c+randInt(-5,6));if(x!==c)wrong.add(x)}return{a,b,c,answers:[c,...wrong].sort(()=>Math.random()-.5)}}
  function startDroneGame(){minigameIntro.classList.add("hidden");minigameResult.classList.add("hidden");droneGame.classList.remove("hidden");droneGame.dataset.finished="0";currentDroneProblem=makeDroneProblem();currentMinigameScores=[];droneA.textContent=`${currentDroneProblem.a} km`;droneB.textContent=`${currentDroneProblem.b} km`;droneQuestion.textContent=`O drone percorre ${currentDroneProblem.a} km e depois ${currentDroneProblem.b} km em ruas perpendiculares. Qual é a distância direta?`;droneAnswers.innerHTML="";currentDroneProblem.answers.forEach(v=>{const b=document.createElement("button");b.type="button";b.className="final-drone-answer";b.textContent=`${v} km`;b.addEventListener("click",()=>submitDroneAnswer(v,b));droneAnswers.appendChild(b)});droneDeadline=performance.now()+12000;clearInterval(droneTimerId);droneTimerId=setInterval(updateDroneTimer,100);updateDroneTimer()}
  function updateDroneTimer(){const left=Math.max(0,droneDeadline-performance.now());droneTimer.textContent=`Tempo: ${(left/1000).toFixed(1)} s`;if(left<=0){clearInterval(droneTimerId);submitDroneAnswer(null,null)}}
  const botAccuracy=b=>({easy:.45,normal:.70,hard:.90}[b.difficulty]||.70);
  function submitDroneAnswer(value,button){if(!currentDroneProblem||droneGame.dataset.finished==="1")return;droneGame.dataset.finished="1";clearInterval(droneTimerId);$$('.final-drone-answer',droneAnswers).forEach(b=>b.disabled=true);const correct=value===currentDroneProblem.c;if(button)button.classList.add(correct?"correct":"wrong");$$('.final-drone-answer',droneAnswers).find(b=>b.textContent===`${currentDroneProblem.c} km`)?.classList.add("correct");const reaction=Math.max(250,12000-Math.max(0,droneDeadline-performance.now())),humans=state.players.filter(p=>p.human),bots=state.players.filter(p=>p.bot);humans.forEach((p,i)=>currentMinigameScores.push({player:p,correct:i===0?correct:false,timeMs:i===0?reaction:12000,performance:i===0&&correct?10000-reaction:0}));bots.forEach(bot=>{const ok=Math.random()<botAccuracy(bot),base=({easy:8000,normal:5900,hard:4000}[bot.difficulty]||5900),time=Math.max(800,base+randInt(-1400,1400));currentMinigameScores.push({player:bot,correct:ok,timeMs:time,performance:ok?10000-time:0})});setTimeout(showMinigameResults,850)}
  function showMinigameResults(){currentDroneProblem=null;droneGame.classList.add("hidden");minigameResult.classList.remove("hidden");currentMinigameScores.sort((a,b)=>b.performance-a.performance||a.timeMs-b.timeMs);const winner=currentMinigameScores.find(e=>e.correct)||currentMinigameScores[0];if(winner?.player){winner.player.score+=MINIGAME_REWARD;minigameWinner.textContent=`${winner.player.name} venceu!`}else minigameWinner.textContent="Ninguém acertou desta vez.";minigameRanking.innerHTML="";currentMinigameScores.forEach((e,i)=>{const row=document.createElement("div");row.className="final-ranking-row";row.innerHTML=`<b>${i+1}º</b><span><strong></strong><small></small></span><span>${e.correct?"✓":"×"}</span>`;$("strong",row).textContent=e.player.name;$("small",row).textContent=e.correct?`${(e.timeMs/1000).toFixed(1)} s`:"Errou";minigameRanking.appendChild(row)});renderPlayers()}
  function closeMinigame(){clearInterval(droneTimerId);minigameOverlay.classList.add("hidden");advanceRound()}
  function finishMatch(){matchResultOverlay.classList.remove("hidden");const sorted=[...state.players].sort((a,b)=>b.score-a.score||b.laps-a.laps);matchRanking.innerHTML="";sorted.forEach((p,i)=>{const row=document.createElement("div");row.className="final-ranking-row";row.innerHTML=`<b>${i+1}º</b><span><strong></strong><small></small></span><span><strong>${p.score} pts</strong></span>`;const info=$('span',row);$('strong',info).textContent=p.name;$('small',row).textContent=p.bot?`Bot • ${difficultyLabel(p.difficulty)}`:"Humano";matchRanking.appendChild(row)})}
  function leaveBoard(){clearInterval(droneTimerId);state=null;view.classList.add("hidden");minigameOverlay.classList.add("hidden");matchResultOverlay.classList.add("hidden");api().showView?.("main")}
  function start(match=null){const saved=match||JSON.parse(localStorage.getItem(MATCH_KEY)||"{}");if(!saved?.humanPlayers){toast("Configure a partida primeiro.");return false}if(saved.mode!=="local"||saved.controlMethod!=="keyboard"){toast("O tabuleiro novo com celulares entra na próxima etapa. Abrindo o protótipo conectado atual.");return false}state={match:saved,players:buildPlayers(saved),round:1,totalRounds:Math.max(1,Number(saved.rounds||BOARD_CONFIG.defaultRounds||5)),turnIndex:0,currentMinigame:null};renderSpaces();renderTokens();modeBadge.textContent="Local";eventBox.textContent="Partida iniciada. O dado possui 6 faces visuais e resultados de 1 a 10.";matchResultOverlay.classList.add("hidden");minigameOverlay.classList.add("hidden");api().showView?.("board");updateTurnUi();return true}
  rollButton?.addEventListener("click",rollForCurrentPlayer);$("#finalStartMinigame")?.addEventListener("click",()=>{if(state?.currentMinigame?.id==="drone-route")startDroneGame()});$("#finalReturnBoard")?.addEventListener("click",closeMinigame);$("#finalBoardExit")?.addEventListener("click",leaveBoard);$("#finalMatchBackMenu")?.addEventListener("click",leaveBoard);
  window.STEAMPartyBoard={start,rollForCurrentPlayer};
})();
